[package]
name = "mat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="mat"
path="src/lib.rs"

[[bin]]
name="mat_test"
path="src/main.rs"


[dependencies]
thiserror = "1.0.38"
